export const contractAddress = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS;

export const contractABI = [
	{
		inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
		name: "cancelCampaign",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_title", type: "string" },
			{ internalType: "string", name: "_description", type: "string" },
			{ internalType: "uint256", name: "_target", type: "uint256" },
			{ internalType: "uint256", name: "_deadline", type: "uint256" },
			{ internalType: "string", name: "_image", type: "string" },
			{ internalType: "address", name: "_token", type: "address" },
			{ internalType: "string", name: "_tokenSymbol", type: "string" },
			{ internalType: "string", name: "_tokenImage", type: "string" },
			{ internalType: "uint256", name: "_tokensPerEth", type: "uint256" },
			{ internalType: "string[]", name: "_milestoneTitles", type: "string[]" },
			{ internalType: "uint256[]", name: "_milestoneAmounts", type: "uint256[]" },
		],
		name: "createCampaign",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_title", type: "string" },
			{ internalType: "string", name: "_description", type: "string" },
			{ internalType: "uint256", name: "_target", type: "uint256" },
			{ internalType: "uint256", name: "_deadline", type: "uint256" },
			{ internalType: "string", name: "_image", type: "string" },
			{ internalType: "string", name: "_tokenName", type: "string" },
			{ internalType: "string", name: "_tokenSymbol", type: "string" },
			{ internalType: "string", name: "_tokenImage", type: "string" },
			{ internalType: "uint256", name: "_tokensPerEth", type: "uint256" },
			{ internalType: "string[]", name: "_milestoneTitles", type: "string[]" },
			{ internalType: "uint256[]", name: "_milestoneAmounts", type: "uint256[]" },
		],
		name: "createCampaignWithToken",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
		name: "donateToCampaign",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
		name: "getCampaign",
		outputs: [
			{ internalType: "address", name: "owner", type: "address" },
			{ internalType: "string", name: "title", type: "string" },
			{ internalType: "string", name: "description", type: "string" },
			{ internalType: "uint256", name: "target", type: "uint256" },
			{ internalType: "uint256", name: "deadline", type: "uint256" },
			{ internalType: "uint256", name: "amountCollected", type: "uint256" },
			{ internalType: "string", name: "image", type: "string" },
			{ internalType: "address", name: "token", type: "address" },
			{ internalType: "string", name: "tokenSymbol", type: "string" },
			{ internalType: "string", name: "tokenImage", type: "string" },
			{ internalType: "uint256", name: "tokensPerEth", type: "uint256" },
			{ internalType: "bool", name: "cancelled", type: "bool" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "getCampaigns",
		outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
		name: "getDonators",
		outputs: [
			{ internalType: "address[]", name: "", type: "address[]" },
			{ internalType: "uint256[]", name: "", type: "uint256[]" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
		name: "getMilestones",
		outputs: [
			{
				components: [
					{ internalType: "string", name: "title", type: "string" },
					{ internalType: "uint256", name: "amount", type: "uint256" },
					{ internalType: "uint256", name: "voteWeight", type: "uint256" },
					{ internalType: "bool", name: "released", type: "bool" },
				],
				internalType: "struct CrowdfundingTokenized.Milestone[]",
				name: "",
				type: "tuple[]",
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "numberOfCampaigns",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
		name: "refund",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_id", type: "uint256" },
			{ internalType: "uint256", name: "_milestoneId", type: "uint256" },
		],
		name: "releaseMilestone",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_id", type: "uint256" },
			{ internalType: "uint256", name: "_milestoneId", type: "uint256" },
		],
		name: "voteMilestone",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
];